I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/chapters/chapter_0.rpy", line 114, in script
    with fadein
  File "game/scripts/chapters/chapter_0.rpy", line 114, in <module>
    with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/chapters/chapter_0.rpy", line 114, in script
    with fadein
  File "C:\Users\cryst\OneDrive\Desktop\L0veRavenRenPy\- RenPy\renpy\ast.py", line 1360, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\cryst\OneDrive\Desktop\L0veRavenRenPy\- RenPy\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\cryst\OneDrive\Desktop\L0veRavenRenPy\- RenPy\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/chapters/chapter_0.rpy", line 114, in <module>
    with fadein
NameError: name 'fadein' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
My Love 1.0
Thu May  1 14:40:37 2025
